import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { analysisId, format, isPro, chapter4Text, chapter5Text, citations } = await req.json();

    // Build document content
    let content = '';

    // Title page
    content += 'THESIS DOCUMENT\n\n';
    content += '=' .repeat(50) + '\n\n';

    // Chapter 4
    content += 'CHAPTER 4: RESULTS AND DATA ANALYSIS\n\n';
    content += chapter4Text || 'Chapter 4 content not available.\n';
    content += '\n\n';

    // Chapter 5
    content += 'CHAPTER 5: DISCUSSION AND CONCLUSION\n\n';
    content += chapter5Text || 'Chapter 5 content not available.\n';
    content += '\n\n';

    // References (PRO only)
    if (isPro && citations && citations.length > 0) {
      content += 'REFERENCES\n\n';
      const sortedCitations = [...citations].sort((a: any, b: any) => 
        (a.author || '').localeCompare(b.author || '')
      );
      for (const c of sortedCitations) {
        content += `${c.author} (${c.year}). ${c.title}. ${c.journal || ''}.\n`;
        if (c.doi) content += `  https://doi.org/${c.doi}\n`;
        content += '\n';
      }
    }

    // Watermark for free users
    if (!isPro) {
      content += '\n\n---\nGenerated by SPSS AI Platform\n';
    }

    return new Response(JSON.stringify({ content, format }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
